rules:
  color-hex-case: lower
  color-hex-length: short
  color-named: never
  color-no-hex: true
  color-no-invalid-hex: true

  font-family-name-quotes: always-unless-keyword

  font-weight-notation: named-where-possible

  function-blacklist:
    - calc
  function-calc-no-unspaced-operator: true
  function-comma-newline-after: never-multi-line
  function-comma-newline-before: never-multi-line
  function-comma-space-after: always
  function-comma-space-before: never
  function-linear-gradient-no-nonstandard-direction: true
  function-max-empty-lines: 0
  function-name-case: lower
  function-parentheses-newline-inside: never-multi-line
  function-parentheses-space-inside: never
  # function-url-data-uris
  # function-url-no-scheme-relative
  function-url-quotes: always
  # function-url-scheme-whitelist
  # function-whitelist
  function-whitespace-after: always

  number-leading-zero: always
  number-max-precision: 6
  number-no-trailing-zeros: true

  string-no-newline: true
  string-quotes: single

  # length-zero-no-unit

  # time-no-imperceptible

  # unit-blacklist
  unit-case: lower
  unit-no-unknown: true
  # unit-whitelist

  value-keyword-case: lower
  value-no-vendor-prefix: true

  value-list-comma-newline-after: never-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0

  custom-property-empty-line-before: always
  # custom-property-no-outside-root
  # custom-property-pattern

  shorthand-property-no-redundant-values: true

  # property-blacklist
  property-case: lower
  property-no-unknown: true
  property-no-vendor-prefix: true
  # property-whitelist

  keyframe-declaration-no-important: true

  declaration-bang-space-after: never
  declaration-bang-space-before: always
  # declaration-colon-newline-after
  declaration-colon-space-after: always
  declaration-colon-space-before: never
  declaration-empty-line-before:
    - always
    -
      except:
        - after-declaration
        - first-nested
      ignore:
        - after-comment
  declaration-no-important: true
  # declaration-property-unit-blacklist
  # declaration-property-unit-whitelist
  # declaration-property-value-blacklist

  declaration-block-no-duplicate-properties:
    - true
    - ignore:
        - consecutive-duplicates-with-different-values
  declaration-block-no-ignored-properties: true
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never
  declaration-block-single-line-max-declarations: 0
  declaration-block-trailing-semicolon: always

  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after:
    - always-multi-line
    - ignoreAtRules:
      - if
      - else
  block-closing-brace-newline-before: always-multi-line
  block-closing-brace-space-after: always-single-line
  block-closing-brace-space-before: always-single-line
  block-no-empty: true
  block-no-single-line: true
  block-opening-brace-newline-after: always
  # block-opening-brace-newline-before
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always

  selector-attribute-brackets-space-inside: never
  # selector-attribute-operator-blacklist
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  # selector-attribute-operator-whitelist
  # selector-attribute-quotes
  # selector-class-pattern
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  # selector-id-pattern
  selector-max-compound-selectors: 5
  # selector-max-specificity
  # selector-nested-pattern
  # selector-no-attribute
  # selector-no-combinator
  # selector-no-id
  # selector-no-qualifying-type
  # selector-no-type
  selector-no-universal: true
  selector-no-vendor-prefix: true
  # selector-pseudo-class-blacklist
  selector-pseudo-class-case: lower
  selector-pseudo-class-no-unknown: true
  selector-pseudo-class-parentheses-space-inside: never
  # selector-pseudo-class-whitelist
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double
  selector-pseudo-element-no-unknown: true
  # selector-root-no-composition
  selector-type-case: lower
  # selector-type-no-unknown
  selector-max-empty-lines: 0

  selector-list-comma-newline-after: always
  selector-list-comma-newline-before: never-multi-line
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never

  # root-no-standard-properties

  rule-nested-empty-line-before:
    - always
    -
      except:
        - first-nested
      ignore:
        - after-comment
  rule-non-nested-empty-line-before: always

  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-case: lower
  media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: true
  media-feature-no-missing-punctuation: true
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always

  # custom-media-pattern

  media-query-list-comma-newline-after: never-multi-line
  media-query-list-comma-newline-before: never-multi-line
  media-query-list-comma-space-after: always
  media-query-list-comma-space-before: never

  # at-rule-blacklist
  at-rule-empty-line-before:
    - always
    - except:
      - first-nested
      - blockless-group
  at-rule-name-case: lower
  # at-rule-name-newline-after
  at-rule-name-space-after: always
  # at-rule-no-unknown
  at-rule-no-vendor-prefix: true
  at-rule-semicolon-newline-after: always
  # at-rule-whitelist

  stylelint-disable-reason: always-after

  comment-empty-line-before: always
  comment-no-empty: true
  comment-whitespace-inside: always
  # comment-word-blacklist

  indentation: 4
  max-empty-lines: 1
  # max-line-length
  max-nesting-depth:
    - 3
    - ignoreAtRules:
      - media
      - include
  # no-browser-hacks
  # no-descending-specificity
  no-duplicate-selectors: true
  no-empty-source: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-indistinguishable-colors: true
  # no-invalid-double-slash-comments
  no-missing-end-of-source-newline: true
  no-unknown-animations: true
  # no-unsupported-browser-features

  # declaration-block-properties-order
