default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: wis
  username: postgres

test:
  <<: *default
  database: wis

production:
  <<: *default
  database: wis
